### ISSUE TITLE
레시피 카드 디자인 예시

### ISSUE THREAD

**Issue by HWON0720** [hellonayeon/recipe-recommend-service#75]
저희가 구상한 레시피 카드 디자인에 적용 가능한 부분이 있는 것 같아 올립니다.

https://codepen.io/adipurdila/pen/MWbeaya
<BR><BR><BR>
---------------------------------------------------------------------------------------------------------------------------------
하기에 코드들 함께 남겨두었습니다.
---------------------------------------------------------------------------------------------------------------------------------
<BR><BR>
CSS
```css
    /* CSS variables */
    :root {
        --card-bg-color: #fff;
        --card-text-color: #070705;
        --dish-type-color: #BB5274;
        --card-shadow: 0 2.8px 2.2px rgba(0, 0, 0, 0.02), 0 6.7px 5.3px rgba(0, 0, 0, 0.028), 0 12.5px 10px rgba(0, 0, 0, 0.035), 0 22.3px 17.9px rgba(0, 0, 0, 0.042), 0 41.8px 33.4px rgba(0, 0, 0, 0.05), 0 100px 80px rgba(0, 0, 0, 0.07);
        --global-radius: 16px;
    }

    /* Presentation styles */
    body {
        background-color: #F2E4E9;
        display: flex;
        height: 100vh;
        align-items: center;
        justify-content: center;
    }

    /* Recipe card */
    .recipe-card {
        background-color: var(--card-bg-color);
        box-shadow: var(--card-shadow);
        border-radius: var(--global-radius);
        color: var(--card-text-color);
        font-family: 'Poppins', sans-serif;
        line-height: 1.5;
        width: 22rem;
    }

    .recipe-card figure {
        width: 100%;
        margin: 0;
        height: 14rem;
        overflow: hidden;
        border-radius: var(--global-radius) var(--global-radius) 0 0;
        margin-bottom: 2rem;
    }

    .recipe-card figure img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .recipe-card h1 {
        margin: 0 1.5rem 2rem 1.5rem;
        font-size: 20px;
        font-weight: 700;
        letter-spacing: -1px;
    }

    .card-meta {
        display: flex;
        justify-content: space-between;
        margin: 0 1.5rem .5rem;
        font-size: 13px;
    }

    .dish-type {
        font-weight: 600;
        letter-spacing: -0.25px;
        color: #fff;
        margin: 0;
        background-color: var(--dish-type-color);
        padding: .25rem 1rem;
        border-radius: 100px;
    }

    .dish-stats {
        list-style: none;
        padding: 0;
        margin: 0;
        display: flex;
        align-items: center;
    }

    .dish-stats li {
        opacity: .75;
        display: flex;
        align-items: center;
        margin-left: 1rem;
    }

    .dish-stats li svg {
        margin-right: .5rem;
    }

    .dish-stats li svg path {
        stroke: var(--card-text-color);
        stroke-opacity: .25;
    }
```
<br>
HTML

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
C
<div class="recipe-card">
    <figure>
        <img src="https://assets.codepen.io/17119/anna-tukhfatullina-food-photographer-stylist-Mzy-OjtCI70-unsplash.jpg"
             alt="Cover image"/>
    </figure>

    <div class="card-meta">
        <p class="dish-type">Dessert</p>

        <ul class="dish-stats">
            <li>
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M8 2C4.6875 2 2 4.6875 2 8C2 11.3125 4.6875 14 8 14C11.3125 14 14 11.3125 14 8C14 4.6875 11.3125 2 8 2Z"
                          stroke-miterlimit="10"/>
                    <path d="M8 4V8.5H11" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
                2.5hrs
            </li>
            <li>
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M4.9713 2.5C7.00005 2.5 8.00005 4.5 8.00005 4.5C8.00005 4.5 9.00005 2.5 11.0288 2.5C12.6775 2.5 13.9832 3.87937 14 5.52531C14.0344 8.94187 11.2897 11.3716 8.2813 13.4134C8.19836 13.4699 8.10036 13.5 8.00005 13.5C7.89973 13.5 7.80174 13.4699 7.7188 13.4134C4.71067 11.3716 1.96598 8.94187 2.00005 5.52531C2.01692 3.87937 3.32255 2.5 4.9713 2.5Z"
                          stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
                237
            </li>
        </ul>
    </div> <!-- end card-meta -->

    <h1>Delicious Cake with Pistachio and Raspberries</h1>
</div>  <!-- end recipe-card -->
</body>
</html>
```
